// default package
// Generated May 27, 2016 5:11:05 PM by Hibernate Tools 4.3.1.Final
package pojo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private String username;
	private String password;
	private String status;
	private String profile;
	private Set relationshipsForUsername1 = new HashSet(0);
	private Set relationshipsForUsername2 = new HashSet(0);
	private Set groupChats = new HashSet(0);

	public Member() {
	}

	public Member(String username, String password, String status) {
		this.username = username;
		this.password = password;
		this.status = status;
	}

	public Member(String username, String password, String status, String profile,
			Set relationshipsForUsername1, Set relationshipsForUsername2, Set groupChats) {
		this.username = username;
		this.password = password;
		this.status = status;
		this.profile = profile;
		this.relationshipsForUsername1 = relationshipsForUsername1;
		this.relationshipsForUsername2 = relationshipsForUsername2;
		this.groupChats = groupChats;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getProfile() {
		return this.profile;
	}

	public void setProfile(String profile) {
		this.profile = profile;
	}

	public Set getRelationshipsForUsername1() {
		return this.relationshipsForUsername1;
	}

	public void setRelationshipsForUsername1(Set relationshipsForUsername1) {
		this.relationshipsForUsername1 = relationshipsForUsername1;
	}

	public Set getRelationshipsForUsername2() {
		return this.relationshipsForUsername2;
	}

	public void setRelationshipsForUsername2(Set relationshipsForUsername2) {
		this.relationshipsForUsername2 = relationshipsForUsername2;
	}

	public Set getGroupChats() {
		return this.groupChats;
	}

	public void setGroupChats(Set groupChats) {
		this.groupChats = groupChats;
	}

}
