// default package
// Generated May 27, 2016 5:11:05 PM by Hibernate Tools 4.3.1.Final
package pojo;

import java.io.Serializable;

/**
 * Relationship generated by hbm2java
 */
public class Relationship implements java.io.Serializable {

	private RelationshipId id;
	private Member memberByUsername1;
	private Member memberByUsername2;
	private String message;

	public Relationship() {
	}

	public Relationship(RelationshipId id, Member memberByUsername1, Member memberByUsername2) {
		this.id = id;
		this.memberByUsername1 = memberByUsername1;
		this.memberByUsername2 = memberByUsername2;
	}

	public Relationship(RelationshipId id, Member memberByUsername1, Member memberByUsername2, String message) {
		this.id = id;
		this.memberByUsername1 = memberByUsername1;
		this.memberByUsername2 = memberByUsername2;
		this.message = message;
	}

	public RelationshipId getId() {
		return this.id;
	}

	public void setId(RelationshipId id) {
		this.id = id;
	}

	public Member getMemberByUsername1() {
		return this.memberByUsername1;
	}

	public void setMemberByUsername1(Member memberByUsername1) {
		this.memberByUsername1 = memberByUsername1;
	}

	public Member getMemberByUsername2() {
		return this.memberByUsername2;
	}

	public void setMemberByUsername2(Member memberByUsername2) {
		this.memberByUsername2 = memberByUsername2;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
